/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 FD_Blending-Eye_Eyeshadow.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/GLTF_and_bin/FD_Blending-Eye_Eyeshadow.gltf')
  return (
    <group {...props} dispose={null} position={[0, 0.05, 0]} scale={2}>
      <mesh geometry={nodes.FLAUNTBRUSH_40_BLENDING_EYE_EYESHADOW_standard.geometry} material={materials['EPX_150_-_Air_Baked_(with_Carbon_M2_M3_L1_3D_Printers)']} />
      <mesh geometry={nodes.Cylinder001_Cylinder003.geometry} material={materials.brass_pure} position={[0, 0.895, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[105.615, 105.615, 94.754]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.005']} position={[0, 2.003, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1.602, 5.359, 1.437]} />
      <mesh geometry={nodes.Mesh.geometry} material={materials.HAIR} scale={[1.091, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/GLTF_and_bin/FD_Blending-Eye_Eyeshadow.gltf')
