/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 FD_BROWCOMB.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/GLTF_and_bin/FD_Browcomb.gltf')
  return (
    <group {...props} dispose={null} position={[0, 0.05, 0]} scale={2}>
      <mesh geometry={nodes['FLAUNTBRUSH_40_BROWCOMB_&_BRUSH_standard'].geometry} material={materials['EPX_150_-_Air_Baked_(with_Carbon_M2_M3_L1_3D_Printers)']} />
      <mesh geometry={nodes.Cylinder001_Cylinder003.geometry} material={materials.brass_pure} position={[0, 0.673, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[86.751, 86.751, 66.25]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Material} position={[0, 1.497, 0]} scale={0.098}>
        <mesh geometry={nodes.Cube.geometry} material={materials.PLASTIC} position={[-0.164, 4.656, -0.002]} rotation={[0.004, -0.007, -0.532]} scale={[1.479, 1.479, 0.704]} />
        <mesh geometry={nodes.Cube001.geometry} material={materials.PLASTIC} position={[2.386, 6.879, 0]} scale={[1.297, 0.156, 0.137]} />
      </mesh>
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[-0.087, 2.279, 0]} rotation={[0, 0, -1.817]} scale={[-0.322, -0.023, -0.001]} />
      <mesh geometry={nodes.Mesh.geometry} material={materials['Black Hairs']} position={[-0.14, 2.285, 0]} scale={[1, 1, 0.289]} />
    </group>
  )
}

useGLTF.preload('/GLTF_and_bin/FD_BROWCOMB.gltf/FD_Browcomb.gltf')
