/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 FD_FACE.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/GLTF_and_bin/FD_FACE.gltf')
  return (
    <group {...props} dispose={null} position={[0, 0.05, 0]} scale={2} rotation={[0, Math.PI / 2, 0]} >
      <mesh geometry={nodes.FLAUNTBRUSH_40_FACE_standard.geometry} material={materials['EPX_150_-_Air_Baked_(with_Carbon_M2_M3_L1_3D_Printers)']} />
      <mesh geometry={nodes['brass-tube'].geometry} material={materials.Brass} position={[0, 0.467, 0]} scale={[0.337, 0.26, 0.337]} />
      <mesh geometry={nodes.Icosphere.geometry} material={materials.Material} position={[-0.013, 1.552, 0.005]} scale={[0.298, 0.315, 0.348]} />
      <mesh geometry={nodes.Mesh.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/GLTF_and_bin/FD_FACE.gltf')
