/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 FD_Foundation-Bronzer.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/GLTF_and_bin/FD_Foundation-Bronzer.gltf')
  return (
    <group {...props} dispose={null} position={[0, 0.05, 0]} scale={2}>
      <mesh geometry={nodes.FLAUNTBRUSH_40_BRONZER_FOUNDATION_standard.geometry} material={materials['EPX_150_-_Air_Baked_(with_Carbon_M2_M3_L1_3D_Printers)']} />
      <mesh geometry={nodes.BASE_Cylinder001.geometry} material={materials.brass_pure} position={[0, 0.86, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[112.274, 112.274, 63.754]} />
      <mesh geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} position={[0, 1.265, 0]} scale={[0.266, 0.115, 0.112]} />
      <mesh geometry={nodes.Mesh.geometry} material={materials.HAIR} position={[-0.009, 0, 0]} scale={[1.032, 1, 0.941]} />
    </group>
  )
}

useGLTF.preload('/GLTF_and_bin/FD_Foundation-Bronzer.gltf')
